package org.example.lab01.mybatis.dao;

import java.util.List;
import org.example.lab01.mybatis.model.Grupe;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GrupeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int insert(Grupe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    Grupe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    List<Grupe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int updateByPrimaryKey(Grupe record);
}