package org.example.lab01.mybatis.dao;

import java.util.List;
import org.example.lab01.mybatis.model.Pasirenkamaskursas;

public interface PasirenkamaskursasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int insert(Pasirenkamaskursas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    Pasirenkamaskursas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    List<Pasirenkamaskursas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int updateByPrimaryKey(Pasirenkamaskursas record);
}