package org.example.lab01.mybatis.dao;

import java.util.List;
import org.example.lab01.mybatis.model.Studentas;


public interface StudentasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int insert(Studentas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    Studentas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    List<Studentas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    int updateByPrimaryKey(Studentas record);
}