package org.example.lab01.mybatis.model;

public class Grupe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.ID
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.KURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    private Integer kursas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.SPECIALYBE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    private String specialybe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    private Integer grupe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.ID
     *
     * @return the value of PUBLIC.GRUPE.ID
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.ID
     *
     * @param id the value for PUBLIC.GRUPE.ID
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.KURSAS
     *
     * @return the value of PUBLIC.GRUPE.KURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public Integer getKursas() {
        return kursas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.KURSAS
     *
     * @param kursas the value for PUBLIC.GRUPE.KURSAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public void setKursas(Integer kursas) {
        this.kursas = kursas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.SPECIALYBE
     *
     * @return the value of PUBLIC.GRUPE.SPECIALYBE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public String getSpecialybe() {
        return specialybe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.SPECIALYBE
     *
     * @param specialybe the value for PUBLIC.GRUPE.SPECIALYBE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public void setSpecialybe(String specialybe) {
        this.specialybe = specialybe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.GRUPE
     *
     * @return the value of PUBLIC.GRUPE.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public Integer getGrupe() {
        return grupe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.GRUPE
     *
     * @param grupe the value for PUBLIC.GRUPE.GRUPE
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public void setGrupe(Integer grupe) {
        this.grupe = grupe;
    }
}