package org.example.lab01.mybatis.model;

public class Pasirenkamaskursas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASIRENKAMASKURSAS.ID
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASIRENKAMASKURSAS.PAVADINIMAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    private String pavadinimas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASIRENKAMASKURSAS.ID
     *
     * @return the value of PUBLIC.PASIRENKAMASKURSAS.ID
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASIRENKAMASKURSAS.ID
     *
     * @param id the value for PUBLIC.PASIRENKAMASKURSAS.ID
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASIRENKAMASKURSAS.PAVADINIMAS
     *
     * @return the value of PUBLIC.PASIRENKAMASKURSAS.PAVADINIMAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASIRENKAMASKURSAS.PAVADINIMAS
     *
     * @param pavadinimas the value for PUBLIC.PASIRENKAMASKURSAS.PAVADINIMAS
     *
     * @mbg.generated Tue Apr 09 09:17:21 EEST 2024
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }
}